# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/claudiocamolese/Desktop/CUDA-CNN-implementation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/claudiocamolese/Desktop/CUDA-CNN-implementation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/claudiocamolese/Desktop/CUDA-CNN-implementation/CMakeFiles /home/claudiocamolese/Desktop/CUDA-CNN-implementation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/claudiocamolese/Desktop/CUDA-CNN-implementation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cnn_baseline

# Build rule for target.
cnn_baseline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cnn_baseline
.PHONY : cnn_baseline

# fast build rule for target.
cnn_baseline/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/build
.PHONY : cnn_baseline/fast

src/baseline_cuda/kernels/backward.o: src/baseline_cuda/kernels/backward.cu.o
.PHONY : src/baseline_cuda/kernels/backward.o

# target to build an object file
src/baseline_cuda/kernels/backward.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/backward.cu.o
.PHONY : src/baseline_cuda/kernels/backward.cu.o

src/baseline_cuda/kernels/backward.i: src/baseline_cuda/kernels/backward.cu.i
.PHONY : src/baseline_cuda/kernels/backward.i

# target to preprocess a source file
src/baseline_cuda/kernels/backward.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/backward.cu.i
.PHONY : src/baseline_cuda/kernels/backward.cu.i

src/baseline_cuda/kernels/backward.s: src/baseline_cuda/kernels/backward.cu.s
.PHONY : src/baseline_cuda/kernels/backward.s

# target to generate assembly for a file
src/baseline_cuda/kernels/backward.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/backward.cu.s
.PHONY : src/baseline_cuda/kernels/backward.cu.s

src/baseline_cuda/kernels/forward.o: src/baseline_cuda/kernels/forward.cu.o
.PHONY : src/baseline_cuda/kernels/forward.o

# target to build an object file
src/baseline_cuda/kernels/forward.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/forward.cu.o
.PHONY : src/baseline_cuda/kernels/forward.cu.o

src/baseline_cuda/kernels/forward.i: src/baseline_cuda/kernels/forward.cu.i
.PHONY : src/baseline_cuda/kernels/forward.i

# target to preprocess a source file
src/baseline_cuda/kernels/forward.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/forward.cu.i
.PHONY : src/baseline_cuda/kernels/forward.cu.i

src/baseline_cuda/kernels/forward.s: src/baseline_cuda/kernels/forward.cu.s
.PHONY : src/baseline_cuda/kernels/forward.s

# target to generate assembly for a file
src/baseline_cuda/kernels/forward.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/kernels/forward.cu.s
.PHONY : src/baseline_cuda/kernels/forward.cu.s

src/baseline_cuda/main.o: src/baseline_cuda/main.cu.o
.PHONY : src/baseline_cuda/main.o

# target to build an object file
src/baseline_cuda/main.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/main.cu.o
.PHONY : src/baseline_cuda/main.cu.o

src/baseline_cuda/main.i: src/baseline_cuda/main.cu.i
.PHONY : src/baseline_cuda/main.i

# target to preprocess a source file
src/baseline_cuda/main.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/main.cu.i
.PHONY : src/baseline_cuda/main.cu.i

src/baseline_cuda/main.s: src/baseline_cuda/main.cu.s
.PHONY : src/baseline_cuda/main.s

# target to generate assembly for a file
src/baseline_cuda/main.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/baseline_cuda/main.cu.s
.PHONY : src/baseline_cuda/main.cu.s

src/utils/load_data.o: src/utils/load_data.cu.o
.PHONY : src/utils/load_data.o

# target to build an object file
src/utils/load_data.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/utils/load_data.cu.o
.PHONY : src/utils/load_data.cu.o

src/utils/load_data.i: src/utils/load_data.cu.i
.PHONY : src/utils/load_data.i

# target to preprocess a source file
src/utils/load_data.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/utils/load_data.cu.i
.PHONY : src/utils/load_data.cu.i

src/utils/load_data.s: src/utils/load_data.cu.s
.PHONY : src/utils/load_data.s

# target to generate assembly for a file
src/utils/load_data.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cnn_baseline.dir/build.make CMakeFiles/cnn_baseline.dir/src/utils/load_data.cu.s
.PHONY : src/utils/load_data.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... cnn_baseline"
	@echo "... src/baseline_cuda/kernels/backward.o"
	@echo "... src/baseline_cuda/kernels/backward.i"
	@echo "... src/baseline_cuda/kernels/backward.s"
	@echo "... src/baseline_cuda/kernels/forward.o"
	@echo "... src/baseline_cuda/kernels/forward.i"
	@echo "... src/baseline_cuda/kernels/forward.s"
	@echo "... src/baseline_cuda/main.o"
	@echo "... src/baseline_cuda/main.i"
	@echo "... src/baseline_cuda/main.s"
	@echo "... src/utils/load_data.o"
	@echo "... src/utils/load_data.i"
	@echo "... src/utils/load_data.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

